# Generated by Django 5.2.5 on 2025-09-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('rekordapp', '0002_rename_emails_organization_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=100)),
                ('eventdescription', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('eventdate', models.CharField(max_length=12)),
                ('eventicon', models.ImageField(upload_to='icons/')),
                ('organizationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='rekordapp.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
