# Generated by Django 5.2.6 on 2025-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventparticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='eventreport',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventtype',
            field=models.CharField(default='Virtual', max_length=20),
            preserve_default=False,
        ),
    ]
