# Generated by Django 5.2.5 on 2025-10-04 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_event_eventparticipants_event_eventreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventtoken',
            fields=[
                ('tokenid', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtoken', to='mainapp.event')),
            ],
        ),
    ]
