# Generated by Django 5.2.5 on 2025-10-04 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_eventtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoken',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
