# Generated by Django 5.2.5 on 2025-10-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_eventtoken_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtoken',
            old_name='token',
            new_name='claimurl',
        ),
    ]
