# Generated by Django 5.2.6 on 2025-12-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_token_eventtoken_claimurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoken',
            name='claimpass',
            field=models.CharField(default='eventtoken', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventreport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
