# Generated by Django 5.2.6 on 2025-12-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_eventtoken_claimpass_alter_event_eventicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoken',
            name='name',
            field=models.CharField(default='Tester', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventtoken',
            name='claimpass',
            field=models.CharField(max_length=100),
        ),
    ]
