# Generated by Django 5.2.6 on 2026-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_eventtoken_name_alter_eventtoken_claimpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ipfs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventtoken',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
