# Generated by Django 5.2.5 on 2026-01-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_event_ipfs_alter_eventtoken_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ipfs',
        ),
    ]
