# Generated by Django 5.2.6 on 2026-01-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_event_ipfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventprestige',
            field=models.CharField(blank=True, default='standard', max_length=20),
        ),
    ]
