# Generated by Django 5.2.5 on 2026-01-25 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_event_eventprestige'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoken',
            name='metadata',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
