# Generated by Django 5.2.5 on 2025-09-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekordapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='emails',
            new_name='email',
        ),
    ]
